// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWcA7fzfX6M_jvT1p-a2oo42_w7_cKr9Y',
    appId: '1:258270324235:web:07314bd4165cd75d27490e',
    messagingSenderId: '258270324235',
    projectId: 'flutter-authlogin',
    authDomain: 'flutter-authlogin.firebaseapp.com',
    storageBucket: 'flutter-authlogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6C70Ce-RK-nDv6RmwXtz-JQFWDMIqAA',
    appId: '1:258270324235:android:464b15378a245c9a27490e',
    messagingSenderId: '258270324235',
    projectId: 'flutter-authlogin',
    storageBucket: 'flutter-authlogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVt8UZI7IL8ECK8ZVUEOl2SiLLVNKuro',
    appId: '1:258270324235:ios:c756796a810c707727490e',
    messagingSenderId: '258270324235',
    projectId: 'flutter-authlogin',
    storageBucket: 'flutter-authlogin.appspot.com',
    iosBundleId: 'com.example.loginPageTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvVt8UZI7IL8ECK8ZVUEOl2SiLLVNKuro',
    appId: '1:258270324235:ios:fda7761d5d08ea0e27490e',
    messagingSenderId: '258270324235',
    projectId: 'flutter-authlogin',
    storageBucket: 'flutter-authlogin.appspot.com',
    iosBundleId: 'com.example.loginPageTest.RunnerTests',
  );
}
